name: Tự Động Đóng Gói Plugin Oraxen
on:
  push:
    branches: [ "master", "main" ] # Tự động chạy mỗi khi bạn lưu/sửa code ở nhánh master
  workflow_dispatch: # Tạo thêm nút bấm "Run workflow" để bạn thích tự bấm chạy lúc nào cũng được

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Khởi tạo môi trường JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'gradle' # Bật tính năng nhớ đệm giúp các lần build sau nhanh gấp 3 lần

      - name: Cấp quyền chạy cho Gradlew
        run: chmod +x gradlew

      - name: Tiến hành Build Plugin bằng Gradle
        run: ./gradlew clean build --no-daemon

      - name: Đóng gói và xuất file .JAR ra ngoài
        uses: actions/upload-artifact@v4
        with:
          name: Oraxen-Plugin-Custom
          path: "**/build/libs/*.jar" # Tự động gom tất cả file .jar đã build xong trong thư mục dự án
